# Generated by Django 4.2.5 on 2023-11-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название брэнда')),
                ('description', models.TextField(default='Нет описания')),
                ('contacts', models.CharField(max_length=100, verbose_name='Контакты')),
                ('workers', models.ManyToManyField(blank=True, related_name='brand', to='worker.worker')),
            ],
        ),
    ]
